function Q = calcQmat(dazVar,dvxVar,dvyVar,yaw)
%CALCQMAT
%    Q = CALCQMAT(DAZVAR,DVXVAR,DVYVAR,YAW)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Aug-2017 23:18:06

t2 = cos(yaw);
t3 = sin(yaw);
t4 = dvxVar.*t2.*t3;
t5 = t4-dvyVar.*t2.*t3;
t6 = t2.^2;
t7 = t3.^2;
Q = reshape([dazVar,0.0,0.0,0.0,dvxVar.*t6+dvyVar.*t7,t5,0.0,t5,dvxVar.*t7+dvyVar.*t6],[3, 3]);
