function F = calcFmat(dvx,dvy,yaw)
%CALCFMAT
%    F = CALCFMAT(DVX,DVY,YAW)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    31-Aug-2017 17:22:42

t2 = cos(yaw);
t3 = sin(yaw);
F = reshape([1.0,-dvx.*t3-dvy.*t2,dvx.*t2-dvy.*t3,0.0,1.0,0.0,0.0,0.0,1.0],[3, 3]);
